List<Map<String, dynamic>> fruitelist = [
  {
    "image": "assets/apple.png",
    "name": "apple",
    "price": " 200",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "10",
  },
  {
    "image": "assets/banana.png",
    "name": "banana",
    "price": " 150",
    "rating": "4.5",
    "product": 1,
    "delivery": 20,
    "discount": "30",
  },
  {
    "image": "assets/blackgrapes.png",
    "name": "black grapes",
    "price": " 300",
    "rating": "4.9",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  },
  {
    "image": "assets/bor.png",
    "name": "berry",
    "price": " 50",
    "rating": "4.2",
    "product": 1,
    "delivery": 20,
    "discount": "30",
  },
  {
    "image": "assets/chickoo.png",
    "name": "chickoo",
    "price": " 200",
    "rating": "45.8",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  },
  {
    "image": "assets/grapes.png",
    "name": "grapes",
    "price": " 250",
    "rating": "4.0",
    "product": 1,
    "delivery": 20,
    "discount": "70",
  },
  {
    "image": "assets/jujube.png",
    "name": "jujuba berry",
    "price": " 30",
    "rating": "5.6",
    "product": 1,
    "delivery": 20,
    "discount": "30",
  },
  {
    "image": "assets/mango.png",
    "name": "mango",
    "price": " 1000",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "40",
  },
  {
    "image": "assets/mosambi.png",
    "name": "mosambi",
    "price": " 1200",
    "rating": "5.7",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  },
  {
    "image": "assets/orange.png",
    "name": "orange",
    "price": " 900",
    "rating": "4.8",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  }
];
