List<Map<String, dynamic>> productlist = [
  {
    "image": "assets/khandavi.png",
    "name": "khandavi",
    "price": " 200 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  },
  {
    "image": "assets/chiro.png",
    "name": "gujarati patra",
    "price": " 350 ",
    "rating": "5.6",
    "product": 1,
    "delivery": 20,
    "discount": "10",
  },
  {
    "image": "assets/dhokla.png",
    "name": "dhokla",
    "price": " 500 ",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "30",
  },
  {
    "image": "assets/fafda.png",
    "name": "fafda",
    "price": " 1250 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "40",
  },
  {
    "image": "assets/khakhra.png",
    "name": "khakhra",
    "price": " 250 ",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/home1.png",
    "name": "gujarati thadi",
    "price": " 340  ",
    "rating": "5.8",
    "product": 1,
    "delivery": 20,
    "discount": "60",
  },
  {
    "image": "assets/pav.png",
    "name": "dabeli",
    "price": " 50 ",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "70",
  },
  {
    "image": "assets/samosa.png",
    "name": "samosa",
    "price": " 20 ",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "80",
  },
  {
    "image": "assets/thepla.png",
    "name": "thepla",
    "price": " 10 ",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "90",
  },
  {
    "image": "assets/whitedhokla.png",
    "name": "white-dhokla",
    "price": " 150",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  }
];
