List<Map<String, dynamic>> mplist = [
  {
    "image": "assets/bhopali.png",
    "name": "bhopali-ghost-korma",
    "price": " 200 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "10",
  },
  {
    "image": "assets/daal.png",
    "name": "dal-bafla",
    "price": " 350 ",
    "rating": "5.6",
    "product": 1,
    "delivery": 20,
    "discount": "30",
  },
  {
    "image": "assets/jalebi.png",
    "name": "jalebi",
    "price": " 500 ",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  },
  {
    "image": "assets/kebas.png",
    "name": "seekb-kebas",
    "price": " 1250 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "40",
  },
  {
    "image": "assets/kees.png",
    "name": "bhute ",
    "price": " 250 ",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/mawa.png",
    "name": "mawa-batti",
    "price": " 340  ",
    "rating": "5.8",
    "product": 1,
    "delivery": 20,
    "discount": "60",
  },
  {
    "image": "assets/poha.png",
    "name": "indori poha",
    "price": " 50 ",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "30",
  },
  {
    "image": "assets/puri.png",
    "name": "palak-puri",
    "price": " 20 ",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/saak.png",
    "name": "chaki ki saak",
    "price": " 10 ",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "70",
  },
  {
    "image": "assets/home6.png",
    "name": "malpua",
    "price": " 150",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "80",
  }
];
