List<Map<String, dynamic>> northlist = [
  {
    "image": "assets/bhature.png",
    "name": "chhole-bhature",
    "price": " 150 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "30",
  },
  {
    "image": "assets/dahi.png",
    "name": "dahi-bhala",
    "price": " 350 ",
    "rating": "5.6",
    "product": 1,
    "delivery": 20,
    "discount": "10",
  },
  {
    "image": "assets/keer.png",
    "name": "kheer",
    "price": " 500 ",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  },
  {
    "image": "assets/lalmass.png",
    "name": "lalmass",
    "price": " 220 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "40",
  },
  {
    "image": "assets/mutton.png",
    "name": "mutton-rogon",
    "price": " 250 ",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/palak.png",
    "name": "palak-paneer",
    "price": " 230  ",
    "rating": "5.8",
    "product": 1,
    "delivery": 20,
    "discount": "70",
  },
  {
    "image": "assets/phirni.png",
    "name": "phirni",
    "price": " 50 ",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "30",
  },
  {
    "image": "assets/butter.png",
    "name": "chicken-butter",
    "price": " 200 ",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/rajma.png",
    "name": "rajma chawal",
    "price": " 100",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "60",
  },
  {
    "image": "assets/65.png",
    "name": "chicken-65",
    "price": " 150",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "80",
  }
];
