List<Map<String, dynamic>> panjabilist = [
  {
    "image": "assets/prasad.png",
    "name": "panjabi prasad",
    "price": " 200 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "10",
  },
  {
    "image": "assets/butter.png",
    "name": "butter-chicken",
    "price": " 350 ",
    "rating": "5.6",
    "product": 1,
    "delivery": 20,
    "discount": "30",
  },
  {
    "image": "assets/paratha.png",
    "name": "panjabi parotha",
    "price": " 100 ",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  },
  {
    "image": "assets/fish.png",
    "name": "amaritsari fish",
    "price": " 300 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/dal.png",
    "name": "dal-makhani",
    "price": " 250 ",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "60",
  },
  {
    "image": "assets/tandori.png",
    "name": "paneer-tika",
    "price": " 390  ",
    "rating": "5.8",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  },
  {
    "image": "assets/pakora.png",
    "name": "punjabi pakoda kadhi",
    "price": " 250 ",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "40",
  },
  {
    "image": "assets/rajma.png",
    "name": "rajma-chawal",
    "price": " 120 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/saag.png",
    "name": "sarso da saag",
    "price": " 100",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "70",
  },
  {
    "image": "assets/roti.png",
    "name": "makke di roti",
    "price": " 190",
    "rating": "3.5",
    "product": 1,
    "delivery": 20,
    "discount": "80",
  }
];
