List<Map<String, dynamic>> rajlist = [
  {
    "image": "assets/bajara.png",
    "name": "bajare-roti",
    "price": " 50 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "30",
  },
  {
    "image": "assets/bati.png",
    "name": "dal-batti-churma",
    "price": " 120 ",
    "rating": "5.6",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/gatta.png",
    "name": "gatte ki subji",
    "price": " 80 ",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  },
  {
    "image": "assets/ghever.png",
    "name": "ghever",
    "price": " 200 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "10",
  },
  {
    "image": "assets/ker.png",
    "name": "kair sangri",
    "price": " 250 ",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  },
  {
    "image": "assets/onion.png",
    "name": "onion kachori",
    "price": " 100  ",
    "rating": "5.8",
    "product": 1,
    "delivery": 20,
    "discount": "40",
  },
  {
    "image": "assets/panchkuta.png",
    "name": "panchyukta",
    "price": " 50 ",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/papad.png",
    "name": "papad ki subji",
    "price": " 120 ",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "60",
  },
  {
    "image": "assets/raab.png",
    "name": "raab",
    "price": " 100",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "70",
  },
  {
    "image": "assets/lalmass.png",
    "name": "lalmass",
    "price": " 150",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "90",
  }
];
