List<Map<String, dynamic>> saladlist = [
  {
    "image": "assets/s1.png",
    "name": "vegetable salad",
    "price": " 230",
    "rating": "2.3",
    "product": 1,
    "delivery": 20,
    "discount": "10",
  },
  {
    "image": "assets/s2.png",
    "name": "Veg Tomato Salad",
    "price": " 240",
    "rating": "3.3",
    "product": 1,
    "delivery": 20,
    "discount": "30",
  },
  {
    "image": "assets/s3.png",
    "name": "cucumber veg salad",
    "price": " 140",
    "rating": "4.2",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/s4.png",
    "name": "veg pasata salad",
    "price": " 390",
    "rating": "5.8",
    "product": 1,
    "delivery": 20,
    "discount": "5",
  },
  {
    "image": "assets/s5.png",
    "name": "veg regular salad",
    "price": " 50",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "70",
  },
  {
    "image": "assets/s6.png",
    "name": "veg potato salad",
    "price": " 130",
    "rating": "3.3",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/s7.png",
    "name": "veg mix salad",
    "price": " 150",
    "rating": "3.3",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/s8.png",
    "name": "veg fresh salad",
    "price": " 160",
    "rating": "2.3",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/s9.png",
    "name": "dinner salad",
    "price": " 290",
    "rating": "4.9",
    "product": 1,
    "delivery": 20,
    "discount": "10",
  },
  {
    "image": "assets/s10.png",
    "name": "veg bread salad",
    "price": " 180",
    "rating": "5.2",
    "product": 1,
    "delivery": 20,
    "discount": "40",
  },
];
