List<Map<String, dynamic>> southlist = [
  {
    "image": "assets/65.png",
    "name": "chicken 65",
    "price": " 200 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  },
  {
    "image": "assets/appam.png",
    "name": "appam",
    "price": " 350 ",
    "rating": "5.6",
    "product": 1,
    "delivery": 20,
    "discount": "30",
  },
  {
    "image": "assets/birani.png",
    "name": "haidrabadi \nBiryani",
    "price": " 100 ",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "40",
  },
  {
    "image": "assets/dosa.png",
    "name": "masala Dosa",
    "price": " 250 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "30",
  },
  {
    "image": "assets/idli.png",
    "name": "white Soft Idli",
    "price": " 250 ",
    "rating": "4.3",
    "product": 1,
    "delivery": 20,
    "discount": "20",
  },
  {
    "image": "assets/meduvada.png",
    "name": "mendu-Vada",
    "price": " 190 ",
    "rating": "5.8",
    "product": 1,
    "delivery": 20,
    "discount": "10",
  },
  {
    "image": "assets/rasam.png",
    "name": "tomato Rassam",
    "price": " 250 ",
    "rating": "5.9",
    "product": 1,
    "delivery": 20,
    "discount": "40",
  },
  {
    "image": "assets/sambar.png",
    "name": "veg Samabar",
    "price": " 120 ",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "50",
  },
  {
    "image": "assets/upma.png",
    "name": "upma",
    "price": " 100",
    "rating": "5.3",
    "product": 1,
    "delivery": 20,
    "discount": "10",
  },
  {
    "image": "assets/uttapam.png",
    "name": "uttapam",
    "price": " 190",
    "rating": "3.5",
    "product": 1,
    "delivery": 20,
    "discount": "40",
  }
];
